### ISSUE TITLE
I am getting KeyError: 'up_cross'

### ISSUE THREAD

**Issue by Rajesh1215** [WindVChen/Diff-Harmonization#9]
please help me solving this issue 
Optimize_text_embed:   0% 0/49 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/content/Diff-Harmonization/main.py", line 306, in <module>
    harmon_fun(composite_image, prompts, ldm_stable, diffusion_steps, guidance=guidance, generator=generator,
  File "/content/Diff-Harmonization/main.py", line 46, in run_harmonization_no_evaluator
    out_img, _ = diff_harmon.run(diffusion_model, prompts[0], controller, latent=x_t,
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/content/Diff-Harmonization/diff_harmon.py", line 480, in run
    constraint_text_emb = attention_constraint_text_optimization(init_prompt, model, mask, latent,
  File "/content/Diff-Harmonization/diff_harmon.py", line 367, in attention_constraint_text_optimization
    attention_map_fg = aggregate_attention(prompt, controller, size // 32, ("up", "down"), True, 0).cuda()
  File "/content/Diff-Harmonization/utils.py", line 115, in aggregate_attention
    for item in attention_maps[f"{location}_{'cross' if is_cross else 'self'}"]:
KeyError: 'up_cross'

**Comment by WindVChen** [comment]
Hi @Rajesh1215 ,

Please recheck your version of **diffusers** package. Version 0.9.0 should work well.

Hope this helps!

**Comment by Rajesh1215** [comment]
thank you i will check that

**Comment by Rajesh1215** [comment]
@WindVChen 
i have changed diffusers version but i got different error 
Traceback (most recent call last):
  File "/content/Diff-Harmonization/main.py", line 3, in <module>
    from diffusers import StableDiffusionPipeline, DDIMScheduler
  File "/usr/local/lib/python3.10/dist-packages/diffusers/__init__.py", line 31, in <module>
    from .pipeline_utils import DiffusionPipeline
  File "/usr/local/lib/python3.10/dist-packages/diffusers/pipeline_utils.py", line 38, in <module>
    from .schedulers.scheduling_utils import SCHEDULER_CONFIG_NAME
  File "/usr/local/lib/python3.10/dist-packages/diffusers/schedulers/__init__.py", line 38, in <module>
    from .scheduling_ddpm_flax import FlaxDDPMScheduler
  File "/usr/local/lib/python3.10/dist-packages/diffusers/schedulers/scheduling_ddpm_flax.py", line 80, in <module>
    class FlaxDDPMScheduler(FlaxSchedulerMixin, ConfigMixin):
  File "/usr/local/lib/python3.10/dist-packages/diffusers/schedulers/scheduling_ddpm_flax.py", line 216, in FlaxDDPMScheduler
    key: random.KeyArray,
  File "/usr/local/lib/python3.10/dist-packages/jax/_src/deprecations.py", line 55, in getattr
    raise AttributeError(f"module {module!r} has no attribute {name!r}")
AttributeError: module 'jax.random' has no attribute 'KeyArray'

this is my colab file 
https://colab.research.google.com/drive/1mqu757wKRyvU8nuUDv32eDRPd1J4fu4-?authuser=1#scrollTo=-wCXjcP-eZXr

coulld you please help me to solve this error

**Comment by WindVChen** [comment]
Hi @Rajesh1215 ,

Apology for the delayed response. For the error above, the answer [here](https://stackoverflow.com/questions/78302031/stable-diffusion-attributeerror-module-jax-random-has-no-attribute-keyarray) may help.

Hope it helps.
